spring:
  profiles:
    active: dev
  application:
    name: TEE 1104 Union
    admin:
      enabled: false

info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    encoding: '@project.build.sourceEncoding@'
    java:
      verion: '@java.version@'