server:
  port: 8082

spring:
  liquibase:
    enabled: false
    user: sa
    password:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
        trace: false
  main:
    allow-bean-definition-overriding: true
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:test
      username: sa
      password:
    jpa:
      generate-ddl: true
      show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect
      open-in-view: false
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          format_sql: true
          generate_statistics: false

logging:
  level:
    sql: info
    web: debug
    root: info
    liquibase: info

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: swagger.html
